# Researcher 2: Inference Notebook

이 노트북은 연구자 1 컨테이너가 생성한 `model.pkl`과 `test.csv`를 사용해 추론을 수행하고 `result.csv`를 저장합니다.

## 1. 환경과 경로 설정

Docker 컨테이너에서는 공유 폴더가 `/shared`로 마운트됩니다. 로컬에서 실행할 때는 `mission-result/shared`를 사용합니다.

In [1]:
from pathlib import Path
import sys

CWD = Path.cwd().resolve()
if Path('/shared/model.pkl').exists():
    SHARED_DIR = Path('/shared')
else:
    SHARED_DIR = CWD.parent / 'shared' if (CWD.parent / 'shared').exists() else CWD / 'shared'

if (CWD / 'inference.py').exists():
    RESEARCHER2_DIR = CWD
else:
    RESEARCHER2_DIR = CWD / 'researcher2'

sys.path.insert(0, str(RESEARCHER2_DIR))

MODEL_PATH = SHARED_DIR / 'model.pkl'
TEST_PATH = SHARED_DIR / 'test.csv'
RESULT_PATH = SHARED_DIR / 'result.csv'

print('MODEL_PATH:', MODEL_PATH)
print('TEST_PATH:', TEST_PATH)
print('RESULT_PATH:', RESULT_PATH)

MODEL_PATH: C:\Users\amy\Desktop\sprint\sprint_ai07\미션\미션15\4팀_김도민\mission-result\shared\model.pkl
TEST_PATH: C:\Users\amy\Desktop\sprint\sprint_ai07\미션\미션15\4팀_김도민\mission-result\shared\test.csv
RESULT_PATH: C:\Users\amy\Desktop\sprint\sprint_ai07\미션\미션15\4팀_김도민\mission-result\shared\result.csv

## 2. 입력 파일 확인

연구자 2는 직접 학습 데이터를 사용하지 않습니다. 연구자 1이 만든 모델 파일과 테스트 파일만 확인합니다.

In [2]:
for path in [MODEL_PATH, TEST_PATH]:
    print(path, 'exists =', path.exists())

C:\Users\amy\Desktop\sprint\sprint_ai07\미션\미션15\4팀_김도민\mission-result\shared\model.pkl exists = True
C:\Users\amy\Desktop\sprint\sprint_ai07\미션\미션15\4팀_김도민\mission-result\shared\test.csv exists = True

## 3. 테스트 데이터 확인

추론 대상 데이터의 행 수와 컬럼을 확인합니다.

In [3]:
import pandas as pd

test_df = pd.read_csv(TEST_PATH)
print('test shape:', test_df.shape)
display(test_df.head())

test shape: (3000, 5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,Yes,9,1
1,8,51,Yes,7,2
2,8,91,No,4,5
3,5,79,No,7,8
4,2,72,No,4,3

## 4. 추론 실행

저장된 `model.pkl`을 불러와 `test.csv` 전체 행에 대해 예측을 수행합니다.

In [4]:
from inference import run_inference

result_df = run_inference(
    model_path=MODEL_PATH,
    test_path=TEST_PATH,
    result_path=RESULT_PATH,
)

print('result shape:', result_df.shape)
display(result_df.head())

result shape: (3000, 6)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Predicted Performance Index
0,7,99,Yes,9,1,91.8439
1,8,51,Yes,7,2,45.0717
2,8,91,No,4,5,84.3275
3,5,79,No,7,8,65.5835
4,2,72,No,4,3,47.4301

## 5. 결과 파일 확인

`result.csv`가 생성되었고, 테스트 데이터와 같은 행 개수를 가지는지 확인합니다.

In [5]:
saved_result = pd.read_csv(RESULT_PATH)
print('result.csv exists:', RESULT_PATH.exists())
print('same row count:', len(saved_result) == len(test_df))
display(saved_result.head())

result.csv exists: True
same row count: True

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Predicted Performance Index
0,7,99,Yes,9,1,91.8439
1,8,51,Yes,7,2,45.0717
2,8,91,No,4,5,84.3275
3,5,79,No,7,8,65.5835
4,2,72,No,4,3,47.4301